node {
    def server = Artifactory.server 'sruthitest'
    def rtMaven = Artifactory.newMavenBuild()

    stage 'Build'
        git url: 'https://github.com/jfrogdev/project-examples.git'

    stage 'Artifactory configuration'
        rtMaven.tool = maven // Tool name from Jenkins configuration
        rtMaven.deployer releaseRepo:'example-repo-local', snapshotRepo:'maven-localsnap', server: server
        rtMaven.resolver releaseRepo:'mavensample', snapshotRepo:'maven-snap', server: server
        def buildInfo = Artifactory.newBuildInfo()

    stage 'Exec Maven'
        rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean install', buildInfo: buildInfo

    stage 'Publish build info'
        server.publishBuildInfo buildInfo
}
